"""DeepDeBlur3D GUI.

`__version__` is derived from git tags: by setuptools-scm when the package is
built, by `git describe` when running from a checkout. Nothing here is
hand-maintained; to cut a release, tag the commit.
"""
from __future__ import annotations

import re
import subprocess
from pathlib import Path

__all__ = ["__version__"]


def _guess_next(release: str) -> str:
    """Bump the last numeric component, matching setuptools-scm guess-next-dev."""
    parts = release.split(".")
    for i in range(len(parts) - 1, -1, -1):
        if parts[i].isdigit():
            parts[i] = str(int(parts[i]) + 1)
            return ".".join(parts[: i + 1])
    return release


def _version_from_git() -> str | None:
    """Describe the working tree, for checkouts and editable installs.

    Output is normalized to PEP 440 and follows the same guess-next-dev scheme
    as the build-time version. The two agree on any committed state; on a dirty
    tree setuptools-scm reports the next dev version where this reports the tag
    plus a "+dirty" local segment.
    """
    repo = Path(__file__).resolve().parents[2]
    if not (repo / ".git").exists():
        return None
    try:
        out = subprocess.run(
            ["git", "describe", "--long", "--tags", "--dirty", "--always"],
            cwd=repo, capture_output=True, text=True, timeout=5,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    if out.returncode != 0 or not out.stdout.strip():
        return None

    described = out.stdout.strip()
    dirty = described.endswith("-dirty")
    if dirty:
        described = described[: -len("-dirty")]

    # With --long a tagged history is always "<tag>-<distance>-g<hash>";
    # with no tag at all --always leaves just "<hash>".
    match = re.match(r"^(?P<tag>.+)-(?P<distance>\d+)-g(?P<hash>[0-9a-f]+)$", described)
    if match:
        release = match["tag"].lstrip("v")
        distance = int(match["distance"])
        node = f"g{match['hash']}"
        if distance == 0:
            version = release
            local = "dirty" if dirty else ""
        else:
            version = f"{_guess_next(release)}.dev{distance}"
            local = f"{node}.dirty" if dirty else node
    else:
        version = "0.0.0"
        local = f"g{described}.dirty" if dirty else f"g{described}"

    return f"{version}+{local}" if local else version


def _resolve_version() -> str:
    # In a working tree, git is the truth: an editable install freezes its
    # recorded version at install time and goes stale as commits land.
    from_git = _version_from_git()
    if from_git:
        return from_git

    # Generated by setuptools-scm at build time; present in built/installed trees.
    try:
        from ._version import version as scm_version  # type: ignore
        return scm_version
    except Exception:
        pass

    try:
        from importlib.metadata import version
        return version("deblur3d-gui")
    except Exception:
        pass

    return "0.0.0+unknown"


__version__ = _resolve_version()
